version = 0.1

[default]
[default.build.parameters]
template_file = "infra/template.yaml"
cached = true
parallel = true

[default.validate.parameters]
template_file = "infra/template.yaml"

[dev.deploy.parameters]
template_file = ".aws-sam/build/template.yaml"
stack_name = "exam-prep-mvp-dev"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = "StageName=dev"

[prod.deploy.parameters]
template_file = ".aws-sam/build/template.yaml"
stack_name = "exam-prep-mvp-prod"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
parameter_overrides = "StageName=prod"
